# These are supported funding model platforms

# github: [yourusername]
# patreon: yourusername
# open_collective: project-name
# ko_fi: yourusername
# custom: ['https://www.paypal.me/yourusername', 'https://buy-me-a-coffee/yourusername']
